### ISSUE TITLE
Added statically-linked bin-file for openwrt-21.02

### ISSUE THREAD

**Issue by osnosn** [MarcelCoding/zia#50]
Please add binary file (client & server) for x86-64 and arm64 (aarch64_generic OR aarch64_cortex-a53),   

```
rum command "ldd zia-xxxx" , no required shared libraries.
run command "file zia-xxxxx"
Required :   
  ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked,  
  ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked,  
or   
  ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1,   
  ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-aarch64.so.1,   
```

So it can run in OpenWRT-21.02. (x86-64 and armvirt).

**Comment by MarcelCoding** [comment]
Hi could you try the artefacts of this job: https://github.com/MarcelCoding/zia/actions/runs/3553090221

client: 
- arm64: https://github.com/MarcelCoding/zia/suites/9515750638/artifacts/451811617
- amd64: https://github.com/MarcelCoding/zia/suites/9515750638/artifacts/451811623
server:
- arm64: https://github.com/MarcelCoding/zia/suites/9515750638/artifacts/451811625
- amd64: https://github.com/MarcelCoding/zia/suites/9515750638/artifacts/451811631

**Comment by osnosn** [comment]
```
client:   
  arm64: https://github.com/MarcelCoding/zia/suites/9515750638/artifacts/451811617  
  amd64: https://github.com/MarcelCoding/zia/suites/9515750638/artifacts/451811623  
server:   
  arm64: https://github.com/MarcelCoding/zia/suites/9515750638/artifacts/451811625  
  amd64: https://github.com/MarcelCoding/zia/suites/9515750638/artifacts/451811631  
```
These four files work fine in openWRT-21.02 and 22.03 (x86-64 & armvirt).  
These files cannot be downloaded without logging into github. I hope you can put them in releases.  

------
Openwrt supports wireguard and is easy to configure.   
Here are my startup scripts and configuration files.  
* "run-server.sh" ,  openWRT-21.02 runs in KVM virtual machine of x86-64 architecture. IP 192.168.22.22  
  ```
  #!/bin/sh
  prog=zia-server_x86_64-unknown-linux-gnu
  logfile=log.zia
  selfpath=$(/usr/bin/dirname $(/usr/bin/readlink -f -- $0))
  cd $selfpath
  export ZIA_LISTEN_ADDR=0.0.0.0:9001 # public websocket listener (client -> 
  ZIA_UPSTREAM)
  export ZIA_UPSTREAM=127.0.0.1:9000 # your actual udp service e.g. wireguard listener
  export ZIA_MODE=WS # WS or TCP see client -> ZIA_UPSTREAM
  ./$prog >> $logfile &
  ```
* nginx's  config , Running on the KVM host machine, "http://10.1.2.3:80"  
  The same physical machine as above.  
  ```
  location  /wguard {
    allow all;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    if ($http_upgrade = "websocket" ){
       proxy_pass http://192.168.22.22:9001;
    }
  }
  ```
* "run-client.sh" ,  openWRT-22.03 runs in kvm virtual machine of arm64 architecture.   
  Another physical machine.  
  ```
  #!/bin/sh
  prog=zia-client_aarch64-unknown-linux-gnu
  logfile=log.zia
  selfpath=$(/usr/bin/dirname $(/usr/bin/readlink -f -- $0))
  cd $selfpath
  export ZIA_LISTEN_ADDR=127.0.0.1:9001 # local udp listener
  export ZIA_UPSTREAM=ws://10.1.2.3:80/wguard # your zia server instance (ws(s) or tcp(s))
  # export ZIA_PROXY=http://user:pass@proxy.tld:8080 # optional http(s) proxy
  ./$prog >> $logfile &
  ```
* server side, run in openwrt ` netcat -lup 9000`  
  client side, run in openwrt `netcat -u 127.0.0.1 9001`  
  The two-way communication test is normal during the first connection.
* Re execute two "netcat" commands, and the test fails.
  I kill the zia-client by "kill -9 pid" ("kill pid" not work), and restart it.  the test OK.
  I don't know if this is normal.

------
If you want to test by yourself, the following are the openwrt images (raw format) of the two architectures, which can be started and run in the KVM virtual machine.   
If VMware is used, please convert the image format to vmdk.  
If hyper-v is used, convert it to vhdx.
* [openwrt-22.03.2-armvirt-64-generic-ext4-combined-efi.img.gz](https://github.com/osnosn/3proxy-openwrt/releases/download/v0.9.3/openwrt-22.03.2-armvirt-64-generic-ext4-combined-efi.img.gz)  (9MB).
* [openwrt-21.02.5-x86-64-generic-ext4-combined-efi.img.gz](https://downloads.openwrt.org/releases/21.02.5/targets/x86/64/openwrt-21.02.5-x86-64-generic-ext4-combined-efi.img.gz)  (9MB).

**Comment by MarcelCoding** [comment]
Yeah, I've created a new release with the binaries suffixed with `_static` that are linked statically.
https://github.com/MarcelCoding/zia/releases/tag/v0.2.4 The reason only HTTP proxy is supported is because our school network uses an HTTP proxy, and this whole project was just created to be able to use wireguard from inside my school network. But I've created an issue for socks5 https://github.com/MarcelCoding/zia/issues/53, if it isn't too complicated I am going to do it pretty soon, otherwise, I am currently working on a rewrite with some new features. (The server can provide a list of udp upstream, and the client is going to be able to select wich one it would like to use. that way you don't have to setup an individual instance of zia for every wireguard endpoint - or any other udp endpoint) also a TCP port proxy mode is planned, so I can log into my VM using rdp from school without the need for wireguard (and over an HTTP proxy).

**Comment by MarcelCoding** [comment]
And actually, I also used to use nginx, but with the port of zia exposed directly, I got some MB/s more in performance.

**Comment by osnosn** [comment]
sock5 proxy is not necessary. I just mentioned it.

You should check whether the connection fails if the client's wireguard is reconfigured or restarted. Do you have to restart the zia client to recover.

-------
I use nginx reverse proxy because I have permission to modify this machine, but it has a website running and only TCP/80, 443 can be accessed.

**Comment by MarcelCoding** [comment]
No, I did a big update a long time ago, which shouldn't need a restart of zia anymore if wireguard restarts. If you use an ancient version, this may be the case.

**Comment by testingnic** [comment]
@osnosn hi bro Your nginx configuration helped me a lot but it only works for ws, as it should, it works with tcp using zia


teanks bro
