### ISSUE TITLE
how to run zia on docker?

### ISSUE THREAD

**Issue by italy2010** [MarcelCoding/zia#63]
root@BleachWrt:~# docker run ghcr.io/marcelcoding/zia-client:edge listen_addr = "127.0.0.1:8080"
Error: missing field `listen_addr`

**Comment by MarcelCoding** [comment]
You have to define the configuration as environment variables. Have a look here for a live of all available: https://github.com/MarcelCoding/zia#client

Example:
```bash
docker run --rm -d \
  -e ZIA_LISTEN_ADDR=0.0.0.0:8080 \
  -e ZIA_UPSTREAM=ws://domain.tld:1234 \
  ghcr.io/marcelcoding/zia-client:edge 
```
