### ISSUE TITLE
websocket hearthbeat

### ISSUE THREAD

**Issue by bytejedi** [MarcelCoding/zia#83]
In my case, we use nginx proxy ws, nginx **proxy_read_timeout, proxy_send_timeout**
require a hearthbeat ping every x seconds to maintain websocket connection.
what do you think, any plans?

**Comment by MarcelCoding** [comment]
Idk, UDP is stateless, so there is no benefit in keeping the connection always open. The only problem that I could think of is, that Zia is not recognizing that the websocket connection got closer and still tries to send data over it.

**Comment by MarcelCoding** [comment]
Did you experienced any problems?

**Comment by MarcelCoding** [comment]
@bytejedi anything you would like to say, otherwise I will close this issue.

**Comment by bytejedi** [comment]
> Did you experience any problems? PS: I always route my complete traffic through WireGuard, so there was never any silence for 30 seconds.

There is no problem with wireguard scenarios.
